name = "cityschedules-us"
workers_dev = false
route = { pattern = "cityschedules.us", custom_domain = true }

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[env.staging]
workers_dev = true
